/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.jetbrains.kotlin.jvm") version "1.4.32"
    id("org.openjfx.javafxplugin") version "0.0.9"
    java
    `maven-publish`
    `application`
}

repositories {
    mavenLocal()
    mavenCentral()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    implementation("com.radixpro.enigma:libbe:0.3.3")
    implementation("com.radixpro.enigma:libfe:0.2")
    implementation("de.th-mack:seport:2.01.00-02")
    implementation("org.openjfx:javafx-swing:11.0.2")
    implementation("org.openjfx:javafx-controls:14.0.1")
    implementation("org.openjfx:javafx-fxml:14-ea+8")
    implementation("org.openjfx:javafx-web:14-ea+8")
    implementation("org.openjfx:javafx-graphics:14.0.1")
    implementation("org.controlsfx:controlsfx:11.0.1")
    implementation("org.apache.commons:commons-lang3:3.9")
    implementation("org.slf4j:slf4j-api:1.7.5")
    implementation("org.slf4j:slf4j-log4j12:1.7.5")
    implementation("org.jetbrains:annotations:RELEASE")
    implementation(platform("org.jetbrains.kotlin:kotlin-bom"))
    implementation("org.jetbrains.kotlin:kotlin-stdlib:1.4.32")
//    implementation("io.github.palexdev:materialfx:11.10.1")
//    compile("org.jfxtras:jmetro:11.6.14")
    compile("com.jfoenix:jfoenix:9.0.10")
    testImplementation("org.junit.jupiter:junit-jupiter-engine:5.7.0")
    testImplementation("junit:junit:4.12")
    testImplementation("io.mockk:mockk:1.10.2")
    testImplementation("io.kotest:kotest-assertions-core-jvm:4.3.0")
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit:1.4.32")
    testImplementation("org.junit.jupiter:junit-jupiter:5.7.0")
    compileOnly("org.jetbrains.kotlin:kotlin-maven-plugin:1.4.32")
}

javafx {
    version = "14.0.1"
    modules("javafx.controls", "javafx.web", "javafx.fxml")
}

application {
    // Define the main class for the application.
    mainClass.set("com.radixpro.enigma.AppLauncherKt")
}


group = "com.radixpro.enigma"
version = "1.0-SNAPSHOT"
description = "Cycles"
java.sourceCompatibility = JavaVersion.VERSION_14

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile> {
    options.encoding = "UTF-8"
}

